//! Harvest the ROM symbol table from the annotated disassembly.
//!
//! `doc/ref/Spectrum48-disassembly.asm` names most of the ROM's entry points in the form
//!
//! ```text
//! ;; START-NEW
//! L11CB:  LD      B,A             ; Save the flag to control later branching.
//! ```
//!
//! Turning those pairs into a `&[(u16, &str)]` is what makes a trace read
//! `CALL $0D6B ; CLS` instead of `CALL $0D6B` — the highest debugging value per line of
//! code in the project. If the listing is missing the table comes out empty and everything
//! still works, just anonymously.

use std::path::Path;
use std::{env, fs};

fn main() {
    let listing = Path::new("doc/ref/Spectrum48-disassembly.asm");
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed={}", listing.display());

    let text = fs::read(listing).unwrap_or_default();
    let text = String::from_utf8_lossy(&text);
    let mut symbols = harvest(&text);
    symbols.sort_by_key(|&(addr, _)| addr);
    symbols.dedup_by_key(|&mut (addr, _)| addr);

    let mut out = String::from(
        "// Generated by build.rs from doc/ref/Spectrum48-disassembly.asm.\n\
         /// ROM entry points, sorted by address.\n\
         pub static ROM_SYMBOLS: &[(u16, &str)] = &[\n",
    );
    for (addr, name) in &symbols {
        out.push_str(&format!("    (0x{addr:04X}, \"{}\"),\n", escape(name)));
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("rom_symbols.rs");
    fs::write(&dest, out).expect("write rom_symbols.rs");
}

/// A `;; NAME` line names the `Lxxxx:` label that follows it. Blank lines and further
/// comments may come between the two; anything else means the name was not a label after
/// all, so drop it.
fn harvest(text: &str) -> Vec<(u16, String)> {
    let mut symbols = Vec::new();
    let mut pending: Option<&str> = None;

    for line in text.lines() {
        let trimmed = line.trim_end();
        if let Some(name) = trimmed.strip_prefix(";;") {
            let name = name.trim();
            // `;; NAME` sits alone on its line; a `;; NOTE like this` is prose.
            pending = (!name.is_empty() && !name.contains(char::is_whitespace)).then_some(name);
        } else if let Some(label) = parse_label(trimmed) {
            if let Some(name) = pending.take() {
                symbols.push((label, name.to_string()));
            }
        } else if !trimmed.trim().is_empty() && !trimmed.trim_start().starts_with(';') {
            pending = None;
        }
    }
    symbols
}

/// `L11CB:` at the start of a line → `0x11CB`.
fn parse_label(line: &str) -> Option<u16> {
    let rest = line.strip_prefix('L')?;
    let (hex, _) = rest.split_once(':')?;
    (hex.len() == 4).then(|| u16::from_str_radix(hex, 16).ok())?
}

fn escape(name: &str) -> String {
    name.replace('\\', "\\\\").replace('"', "\\\"")
}
