//! §8.1 of the plan: decode every opcode in every prefix bank and check the result against
//! the generated tables in `doc/z80-instruction-set.md`.
//!
//! All 1792 `(prefix, opcode)` pairs are covered. The expected values come from
//! `tests/fixtures/opcodes.rs`, generated by the same script that generated the tables in
//! the spec — and `fixture_matches_the_spec_document` parses the document itself to prove
//! the two still agree, so a stale fixture is a test failure rather than a silent lie.

use on_the_spectrum::z80::{
    Cond, Decoded, ExOp, Op, Prefix, Reg8, Reg16, RotOp, Src8, decode_bytes, spec_mnemonic,
};

mod fixture {
    include!("fixtures/opcodes.rs");
}

use fixture::Row;

/// Filler for the operand bytes: distinctive, and different in each position so a
/// byte-order mistake shows up as a swapped nibble rather than passing silently.
const N1: u8 = 0x34;
const N2: u8 = 0x12;

/// `mnemonic` is passed separately so the `FD` banks can check against the `DD` row with
/// `IY` substituted for `IX`.
fn check(bytes: &[u8], row: Row, mnemonic: &str, what: &str) {
    let dec = decode_bytes(bytes);
    assert_eq!(
        spec_mnemonic(&dec),
        mnemonic,
        "{what}: wrong mnemonic (decoded {:?})",
        dec.op
    );
    assert_eq!(dec.len, row.bytes, "{what}: wrong length for {mnemonic}");
    assert_eq!(
        !dec.undocumented, row.documented,
        "{what}: wrong documented flag for {mnemonic}"
    );
}

#[test]
fn unprefixed_bank_matches_the_spec() {
    for op in 0..=255u8 {
        // CB, DD, ED and FD are prefixes, not instructions: they never appear on their own.
        if matches!(op, 0xCB | 0xDD | 0xED | 0xFD) {
            continue;
        }
        let row = fixture::UNPREFIXED[op as usize].expect("every unprefixed opcode decodes");
        check(&[op, N1, N2], row, row.mnemonic, &format!("{op:02X}"));
    }
}

#[test]
fn cb_bank_matches_the_spec() {
    for op in 0..=255u8 {
        let row = fixture::CB[op as usize].expect("every CB opcode decodes");
        check(&[0xCB, op], row, row.mnemonic, &format!("CB {op:02X}"));
    }
}

#[test]
fn ed_bank_matches_the_spec() {
    for op in 0..=255u8 {
        let row = fixture::ED[op as usize].expect("every ED opcode decodes");
        check(
            &[0xED, op, N1, N2],
            row,
            row.mnemonic,
            &format!("ED {op:02X}"),
        );
    }
}

#[test]
fn dd_and_fd_banks_match_the_spec() {
    for (prefix, index) in [(0xDDu8, "IX"), (0xFD, "IY")] {
        for op in 0..=255u8 {
            let what = format!("{prefix:02X} {op:02X}");
            match fixture::DD[op as usize] {
                Some(row) => {
                    let expected = row.mnemonic.replace("IX", index);
                    check(&[prefix, op, N1, N2], row, &expected, &what);
                }
                // The prefix does not affect this opcode: it must decode exactly as the
                // unprefixed form, one byte longer.
                None => {
                    if matches!(op, 0xCB | 0xDD | 0xED | 0xFD) {
                        continue; // another bank, tested elsewhere
                    }
                    let prefixed = decode_bytes(&[prefix, op, N1, N2]);
                    let bare = decode_bytes(&[op, N1, N2]);
                    assert_eq!(prefixed.op, bare.op, "{what}: prefix should have no effect");
                    assert_eq!(prefixed.len, bare.len + 1, "{what}: wrong length");
                }
            }
        }
    }
}

#[test]
fn ddcb_and_fdcb_banks_match_the_spec() {
    for (prefix, index) in [(0xDDu8, "IX"), (0xFD, "IY")] {
        for op in 0..=255u8 {
            let row = fixture::DDCB[op as usize].expect("every DDCB opcode decodes");
            let expected = row.mnemonic.replace("IX", index);
            check(
                &[prefix, 0xCB, 0x05, op],
                row,
                &expected,
                &format!("{prefix:02X} CB d {op:02X}"),
            );
        }
    }
}

// ------------------------------------------------------------------ the awkward corners

#[test]
fn index_substitution_spares_the_other_operand() {
    // `LD H,(IX+d)` exists; `LD IXH,(IX+d)` does not.
    let dec = decode_bytes(&[0xDD, 0x66, 0x05]);
    assert_eq!(
        dec.op,
        Op::Load8 {
            dst: Reg8::H,
            src: Src8::Reg(Reg8::MemIdx)
        }
    );
    assert_eq!(dec.disp, 5);

    let dec = decode_bytes(&[0xDD, 0x74, 0xFB]);
    assert_eq!(
        dec.op,
        Op::Load8 {
            dst: Reg8::MemIdx,
            src: Src8::Reg(Reg8::H)
        }
    );
    assert_eq!(dec.disp, -5);

    // With no memory operand in sight, H and L *are* substituted.
    assert_eq!(
        decode_bytes(&[0xDD, 0x65]).op,
        Op::Load8 {
            dst: Reg8::IxH,
            src: Src8::Reg(Reg8::IxL)
        }
    );
}

#[test]
fn ex_de_hl_ignores_the_index_prefix() {
    assert_eq!(decode_bytes(&[0xDD, 0xEB]).op, Op::Ex(ExOp::DeHl));
    assert_eq!(decode_bytes(&[0xFD, 0xEB]).op, Op::Ex(ExOp::DeHl));
    // ...but EX (SP),HL does not.
    assert_eq!(
        decode_bytes(&[0xFD, 0xE3]).op,
        Op::Ex(ExOp::SpReg(Reg16::Iy))
    );
}

#[test]
fn displacement_comes_before_the_immediate() {
    // DD 36 d n — not DD 36 n d.
    let dec = decode_bytes(&[0xDD, 0x36, 0x7F, 0xA5]);
    assert_eq!(dec.disp, 0x7F);
    assert_eq!(
        dec.op,
        Op::Load8 {
            dst: Reg8::MemIdx,
            src: Src8::Imm(0xA5)
        }
    );
    assert_eq!(dec.len, 4);
}

#[test]
fn ddcb_displacement_comes_before_the_opcode() {
    // DD CB d op, and the undocumented form copies the result to a register as well.
    let dec = decode_bytes(&[0xDD, 0xCB, 0xFE, 0x06]);
    assert_eq!(dec.disp, -2);
    assert_eq!(
        dec.op,
        Op::Rot {
            op: RotOp::Rlc,
            target: Reg8::MemIdx,
            copy_to: None
        }
    );
    assert_eq!(
        decode_bytes(&[0xFD, 0xCB, 0x00, 0x86]).op,
        Op::Res {
            bit: 0,
            target: Reg8::MemIdx,
            copy_to: None
        }
    );
    assert_eq!(
        decode_bytes(&[0xFD, 0xCB, 0x00, 0x80]).op,
        Op::Res {
            bit: 0,
            target: Reg8::MemIdx,
            copy_to: Some(Reg8::B)
        }
    );
    assert_eq!(
        spec_mnemonic(&decode_bytes(&[0xFD, 0xCB, 0x00, 0x80])),
        "LD B,RES 0,(IY+d)"
    );
}

#[test]
fn the_last_index_prefix_wins() {
    // Each DD/FD is a NONI that re-arms the substitution, so only the last one matters.
    assert_eq!(decode_bytes(&[0xFD, 0xDD, 0x23]).op, Op::Inc16(Reg16::Ix));
    assert_eq!(decode_bytes(&[0xDD, 0xFD, 0x23]).op, Op::Inc16(Reg16::Iy));
    assert_eq!(decode_bytes(&[0xDD, 0xFD, 0x23]).len, 3);
    // A DD/FD before an ED is discarded entirely.
    let dec = decode_bytes(&[0xDD, 0xED, 0x4A]);
    assert_eq!(dec.op, Op::AdcHl { src: Reg16::Bc });
    assert_eq!(dec.len, 3);
    assert_eq!(dec.prefix, Prefix::Ed);
}

#[test]
fn a_long_prefix_run_stays_addressable() {
    // Real hardware allows an unbounded run; we break it into NONI-NOPs so `len` fits a u8.
    let dec = decode_bytes(&[0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0x23]);
    assert_eq!(dec.op, Op::Nop);
    assert_eq!(dec.len, 4);
    assert_eq!(decode_bytes(&[0xDD, 0x23]).len, 2);
}

#[test]
fn invalid_ed_opcodes_are_two_byte_nops() {
    let dec = decode_bytes(&[0xED, 0x00]);
    assert_eq!(dec.op, Op::Invalid);
    assert_eq!(dec.len, 2);
    assert!(dec.undocumented);
}

#[test]
fn relative_jumps_disassemble_to_absolute_targets() {
    use on_the_spectrum::z80::disassemble;

    // JR NZ,+$43 at $000E lands at $0053.
    let dec = decode_bytes(&[0x20, 0x43]);
    assert_eq!(disassemble(&dec, 0x000E, None), "JR NZ,$0053 ; d=+$43");
    // ...and backwards.
    let dec = decode_bytes(&[0x10, 0xFB]);
    assert_eq!(disassemble(&dec, 0x0100, None), "DJNZ $00FD ; d=-$05");
}

#[test]
fn undocumented_opcodes_are_marked_in_a_listing() {
    use on_the_spectrum::z80::disassemble;

    assert_eq!(disassemble(&decode_bytes(&[0xED, 0x44]), 0, None), "NEG");
    assert_eq!(disassemble(&decode_bytes(&[0xED, 0x4C]), 0, None), "*NEG");
    assert_eq!(disassemble(&decode_bytes(&[0xED, 0x55]), 0, None), "*RETN");
    assert_eq!(disassemble(&decode_bytes(&[0xCB, 0x30]), 0, None), "*SLL B");
    assert_eq!(
        disassemble(&decode_bytes(&[0xED, 0x70]), 0, None),
        "*IN (C)"
    );
    assert_eq!(
        disassemble(&decode_bytes(&[0xED, 0x71]), 0, None),
        "*OUT (C),0"
    );
}

#[test]
fn conditions_and_immediates_render_as_the_listing_does() {
    use on_the_spectrum::z80::disassemble;

    let cases: &[(&[u8], &str)] = &[
        (&[0x2A, 0x5D, 0x5C], "LD HL,($5C5D)"),
        (&[0x22, 0x5F, 0x5C], "LD ($5C5F),HL"),
        (&[0xD3, 0xFE], "OUT ($FE),A"),
        (&[0x3E, 0x07], "LD A,$07"),
        (&[0xDD, 0x36, 0x05, 0xFF], "LD (IX+$05),$FF"),
        (&[0xFD, 0x7E, 0xFD], "LD A,(IY-$03)"),
        (&[0xED, 0x4E], "*IM 0/1"),
        (&[0xC7], "RST $00"),
        (&[0xEF], "RST $28"),
    ];
    for &(bytes, expected) in cases {
        assert_eq!(disassemble(&decode_bytes(bytes), 0, None), expected);
    }
}

#[test]
fn every_op_variant_survives_a_pass_over_the_rom() {
    // Not a correctness check — a crash check. Straight-line decoding of 16K of ROM and
    // data must never panic, and must always make progress.
    let rom = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/roms/48.rom")).unwrap();
    let mut addr = 0usize;
    let mut count = 0;
    while addr < rom.len() {
        let dec: Decoded = decode_bytes(&rom[addr..]);
        assert!(dec.len >= 1);
        let _ = spec_mnemonic(&dec);
        addr += dec.len as usize;
        count += 1;
    }
    assert!(count > 5000, "only {count} instructions in 16K?");
}

#[test]
fn the_reset_vector_disassembles_as_the_annotated_listing_has_it() {
    use on_the_spectrum::z80::disasm;

    let rom = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/roms/48.rom")).unwrap();
    let listing: Vec<String> = disasm::walk(&rom, 0, 0, 0x13)
        .map(|i| disasm::disassemble_parts(&i.decoded, i.addr, None).0)
        .collect();
    assert_eq!(
        listing,
        [
            "DI", // L0000: START
            "XOR A",
            "LD DE,$FFFF",
            "JP $11CB",
            "LD HL,($5C5D)", // L0008: ERROR-1
            "LD ($5C5F),HL",
            "JR $0053",
            "JP $15F2", // L0010: PRINT-A
        ]
    );
}

// -------------------------------------------------------- docs and fixture must agree

/// Parse the generated listing tables back out of the spec document and check the fixture
/// still says the same thing. Without this the fixture could drift from the document it
/// claims to mirror, and the round-trip tests above would be verifying nothing in
/// particular.
#[test]
fn fixture_matches_the_spec_document() {
    let doc = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/doc/z80-instruction-set.md"
    ))
    .unwrap();

    let banks: [(&str, &[Option<Row>; 256]); 5] = [
        ("### Unprefixed opcodes", &fixture::UNPREFIXED),
        ("### `CB`-prefixed opcodes", &fixture::CB),
        ("### `ED`-prefixed opcodes", &fixture::ED),
        ("### `DD`-prefixed opcodes", &fixture::DD),
        ("### `DD CB d`-prefixed opcodes", &fixture::DDCB),
    ];

    for (heading, table) in banks {
        let body = doc
            .split_once(heading)
            .unwrap_or_else(|| panic!("no {heading} section in the spec"))
            .1;
        let rows: Vec<&str> = body
            .lines()
            .skip_while(|l| !l.starts_with("| `"))
            .take_while(|l| l.starts_with("| `"))
            .collect();
        assert_eq!(rows.len(), 256, "{heading}: wrong number of rows");

        for (op, line) in rows.iter().enumerate() {
            let cells: Vec<&str> = line.split('|').map(str::trim).collect();
            let expected = match table[op] {
                None => {
                    assert!(
                        cells[2].starts_with('—'),
                        "{heading} {op:02X}: fixture says the prefix is inert, the doc does not"
                    );
                    continue;
                }
                Some(row) => row,
            };
            assert_eq!(
                cells[2].trim_matches('`'),
                expected.mnemonic,
                "{heading} {op:02X}: mnemonic"
            );
            assert_eq!(
                cells[3].parse::<u8>().ok(),
                Some(expected.bytes),
                "{heading} {op:02X}: bytes"
            );
            assert_eq!(cells[4], expected.tstates, "{heading} {op:02X}: T-states");
            assert_eq!(
                cells[5] == "yes",
                expected.documented,
                "{heading} {op:02X}: documented"
            );
        }
    }
}

#[test]
fn conditions_cover_the_cc_table() {
    // A cheap guard against a transposed condition table: RET cc walks it in order.
    let expected = [
        Cond::Nz,
        Cond::Z,
        Cond::Nc,
        Cond::C,
        Cond::Po,
        Cond::Pe,
        Cond::P,
        Cond::M,
    ];
    for (y, &cond) in expected.iter().enumerate() {
        let op = 0xC0 | (y as u8) << 3;
        assert_eq!(decode_bytes(&[op]).op, Op::Ret { cond });
    }
}
