// Generated by doc/tools/gen_z80.py --- do not edit by hand.
//
//     python3 doc/tools/gen_z80.py rust-fixture > tests/fixtures/opcodes.rs
//
// One row per (prefix, opcode) pair, holding exactly what the generated tables in
// doc/z80-instruction-set.md say: the mnemonic in spec form (`n`, `nn` and `d` left as
// placeholders), the instruction length, the uncontended T-state count, and whether the
// opcode is documented. `None` marks a `DD`/`FD` opcode the prefix does not affect,
// which must decode exactly as the unprefixed opcode does, one byte longer.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Row {
    pub mnemonic: &'static str,
    pub bytes: u8,
    pub tstates: &'static str,
    pub documented: bool,
}

const fn row(mnemonic: &'static str, bytes: u8, tstates: &'static str, documented: bool) -> Option<Row> {
    Some(Row { mnemonic, bytes, tstates, documented })
}


/// Unprefixed opcodes. `CB`/`DD`/`ED`/`FD` are prefixes, not instructions.
pub static UNPREFIXED: [Option<Row>; 256] = [
    row("NOP", 1, "4", true), // 00
    row("LD BC,nn", 3, "10", true), // 01
    row("LD (BC),A", 1, "7", true), // 02
    row("INC BC", 1, "6", true), // 03
    row("INC B", 1, "4", true), // 04
    row("DEC B", 1, "4", true), // 05
    row("LD B,n", 2, "7", true), // 06
    row("RLCA", 1, "4", true), // 07
    row("EX AF,AF'", 1, "4", true), // 08
    row("ADD HL,BC", 1, "11", true), // 09
    row("LD A,(BC)", 1, "7", true), // 0A
    row("DEC BC", 1, "6", true), // 0B
    row("INC C", 1, "4", true), // 0C
    row("DEC C", 1, "4", true), // 0D
    row("LD C,n", 2, "7", true), // 0E
    row("RRCA", 1, "4", true), // 0F
    row("DJNZ d", 2, "13/8", true), // 10
    row("LD DE,nn", 3, "10", true), // 11
    row("LD (DE),A", 1, "7", true), // 12
    row("INC DE", 1, "6", true), // 13
    row("INC D", 1, "4", true), // 14
    row("DEC D", 1, "4", true), // 15
    row("LD D,n", 2, "7", true), // 16
    row("RLA", 1, "4", true), // 17
    row("JR d", 2, "12", true), // 18
    row("ADD HL,DE", 1, "11", true), // 19
    row("LD A,(DE)", 1, "7", true), // 1A
    row("DEC DE", 1, "6", true), // 1B
    row("INC E", 1, "4", true), // 1C
    row("DEC E", 1, "4", true), // 1D
    row("LD E,n", 2, "7", true), // 1E
    row("RRA", 1, "4", true), // 1F
    row("JR NZ,d", 2, "12/7", true), // 20
    row("LD HL,nn", 3, "10", true), // 21
    row("LD (nn),HL", 3, "16", true), // 22
    row("INC HL", 1, "6", true), // 23
    row("INC H", 1, "4", true), // 24
    row("DEC H", 1, "4", true), // 25
    row("LD H,n", 2, "7", true), // 26
    row("DAA", 1, "4", true), // 27
    row("JR Z,d", 2, "12/7", true), // 28
    row("ADD HL,HL", 1, "11", true), // 29
    row("LD HL,(nn)", 3, "16", true), // 2A
    row("DEC HL", 1, "6", true), // 2B
    row("INC L", 1, "4", true), // 2C
    row("DEC L", 1, "4", true), // 2D
    row("LD L,n", 2, "7", true), // 2E
    row("CPL", 1, "4", true), // 2F
    row("JR NC,d", 2, "12/7", true), // 30
    row("LD SP,nn", 3, "10", true), // 31
    row("LD (nn),A", 3, "13", true), // 32
    row("INC SP", 1, "6", true), // 33
    row("INC (HL)", 1, "11", true), // 34
    row("DEC (HL)", 1, "11", true), // 35
    row("LD (HL),n", 2, "10", true), // 36
    row("SCF", 1, "4", true), // 37
    row("JR C,d", 2, "12/7", true), // 38
    row("ADD HL,SP", 1, "11", true), // 39
    row("LD A,(nn)", 3, "13", true), // 3A
    row("DEC SP", 1, "6", true), // 3B
    row("INC A", 1, "4", true), // 3C
    row("DEC A", 1, "4", true), // 3D
    row("LD A,n", 2, "7", true), // 3E
    row("CCF", 1, "4", true), // 3F
    row("LD B,B", 1, "4", true), // 40
    row("LD B,C", 1, "4", true), // 41
    row("LD B,D", 1, "4", true), // 42
    row("LD B,E", 1, "4", true), // 43
    row("LD B,H", 1, "4", true), // 44
    row("LD B,L", 1, "4", true), // 45
    row("LD B,(HL)", 1, "7", true), // 46
    row("LD B,A", 1, "4", true), // 47
    row("LD C,B", 1, "4", true), // 48
    row("LD C,C", 1, "4", true), // 49
    row("LD C,D", 1, "4", true), // 4A
    row("LD C,E", 1, "4", true), // 4B
    row("LD C,H", 1, "4", true), // 4C
    row("LD C,L", 1, "4", true), // 4D
    row("LD C,(HL)", 1, "7", true), // 4E
    row("LD C,A", 1, "4", true), // 4F
    row("LD D,B", 1, "4", true), // 50
    row("LD D,C", 1, "4", true), // 51
    row("LD D,D", 1, "4", true), // 52
    row("LD D,E", 1, "4", true), // 53
    row("LD D,H", 1, "4", true), // 54
    row("LD D,L", 1, "4", true), // 55
    row("LD D,(HL)", 1, "7", true), // 56
    row("LD D,A", 1, "4", true), // 57
    row("LD E,B", 1, "4", true), // 58
    row("LD E,C", 1, "4", true), // 59
    row("LD E,D", 1, "4", true), // 5A
    row("LD E,E", 1, "4", true), // 5B
    row("LD E,H", 1, "4", true), // 5C
    row("LD E,L", 1, "4", true), // 5D
    row("LD E,(HL)", 1, "7", true), // 5E
    row("LD E,A", 1, "4", true), // 5F
    row("LD H,B", 1, "4", true), // 60
    row("LD H,C", 1, "4", true), // 61
    row("LD H,D", 1, "4", true), // 62
    row("LD H,E", 1, "4", true), // 63
    row("LD H,H", 1, "4", true), // 64
    row("LD H,L", 1, "4", true), // 65
    row("LD H,(HL)", 1, "7", true), // 66
    row("LD H,A", 1, "4", true), // 67
    row("LD L,B", 1, "4", true), // 68
    row("LD L,C", 1, "4", true), // 69
    row("LD L,D", 1, "4", true), // 6A
    row("LD L,E", 1, "4", true), // 6B
    row("LD L,H", 1, "4", true), // 6C
    row("LD L,L", 1, "4", true), // 6D
    row("LD L,(HL)", 1, "7", true), // 6E
    row("LD L,A", 1, "4", true), // 6F
    row("LD (HL),B", 1, "7", true), // 70
    row("LD (HL),C", 1, "7", true), // 71
    row("LD (HL),D", 1, "7", true), // 72
    row("LD (HL),E", 1, "7", true), // 73
    row("LD (HL),H", 1, "7", true), // 74
    row("LD (HL),L", 1, "7", true), // 75
    row("HALT", 1, "4", true), // 76
    row("LD (HL),A", 1, "7", true), // 77
    row("LD A,B", 1, "4", true), // 78
    row("LD A,C", 1, "4", true), // 79
    row("LD A,D", 1, "4", true), // 7A
    row("LD A,E", 1, "4", true), // 7B
    row("LD A,H", 1, "4", true), // 7C
    row("LD A,L", 1, "4", true), // 7D
    row("LD A,(HL)", 1, "7", true), // 7E
    row("LD A,A", 1, "4", true), // 7F
    row("ADD A,B", 1, "4", true), // 80
    row("ADD A,C", 1, "4", true), // 81
    row("ADD A,D", 1, "4", true), // 82
    row("ADD A,E", 1, "4", true), // 83
    row("ADD A,H", 1, "4", true), // 84
    row("ADD A,L", 1, "4", true), // 85
    row("ADD A,(HL)", 1, "7", true), // 86
    row("ADD A,A", 1, "4", true), // 87
    row("ADC A,B", 1, "4", true), // 88
    row("ADC A,C", 1, "4", true), // 89
    row("ADC A,D", 1, "4", true), // 8A
    row("ADC A,E", 1, "4", true), // 8B
    row("ADC A,H", 1, "4", true), // 8C
    row("ADC A,L", 1, "4", true), // 8D
    row("ADC A,(HL)", 1, "7", true), // 8E
    row("ADC A,A", 1, "4", true), // 8F
    row("SUB B", 1, "4", true), // 90
    row("SUB C", 1, "4", true), // 91
    row("SUB D", 1, "4", true), // 92
    row("SUB E", 1, "4", true), // 93
    row("SUB H", 1, "4", true), // 94
    row("SUB L", 1, "4", true), // 95
    row("SUB (HL)", 1, "7", true), // 96
    row("SUB A", 1, "4", true), // 97
    row("SBC A,B", 1, "4", true), // 98
    row("SBC A,C", 1, "4", true), // 99
    row("SBC A,D", 1, "4", true), // 9A
    row("SBC A,E", 1, "4", true), // 9B
    row("SBC A,H", 1, "4", true), // 9C
    row("SBC A,L", 1, "4", true), // 9D
    row("SBC A,(HL)", 1, "7", true), // 9E
    row("SBC A,A", 1, "4", true), // 9F
    row("AND B", 1, "4", true), // A0
    row("AND C", 1, "4", true), // A1
    row("AND D", 1, "4", true), // A2
    row("AND E", 1, "4", true), // A3
    row("AND H", 1, "4", true), // A4
    row("AND L", 1, "4", true), // A5
    row("AND (HL)", 1, "7", true), // A6
    row("AND A", 1, "4", true), // A7
    row("XOR B", 1, "4", true), // A8
    row("XOR C", 1, "4", true), // A9
    row("XOR D", 1, "4", true), // AA
    row("XOR E", 1, "4", true), // AB
    row("XOR H", 1, "4", true), // AC
    row("XOR L", 1, "4", true), // AD
    row("XOR (HL)", 1, "7", true), // AE
    row("XOR A", 1, "4", true), // AF
    row("OR B", 1, "4", true), // B0
    row("OR C", 1, "4", true), // B1
    row("OR D", 1, "4", true), // B2
    row("OR E", 1, "4", true), // B3
    row("OR H", 1, "4", true), // B4
    row("OR L", 1, "4", true), // B5
    row("OR (HL)", 1, "7", true), // B6
    row("OR A", 1, "4", true), // B7
    row("CP B", 1, "4", true), // B8
    row("CP C", 1, "4", true), // B9
    row("CP D", 1, "4", true), // BA
    row("CP E", 1, "4", true), // BB
    row("CP H", 1, "4", true), // BC
    row("CP L", 1, "4", true), // BD
    row("CP (HL)", 1, "7", true), // BE
    row("CP A", 1, "4", true), // BF
    row("RET NZ", 1, "11/5", true), // C0
    row("POP BC", 1, "10", true), // C1
    row("JP NZ,nn", 3, "10", true), // C2
    row("JP nn", 3, "10", true), // C3
    row("CALL NZ,nn", 3, "17/10", true), // C4
    row("PUSH BC", 1, "11", true), // C5
    row("ADD A,n", 2, "7", true), // C6
    row("RST 00h", 1, "11", true), // C7
    row("RET Z", 1, "11/5", true), // C8
    row("RET", 1, "10", true), // C9
    row("JP Z,nn", 3, "10", true), // CA
    row("*CB prefix*", 1, "-", true), // CB
    row("CALL Z,nn", 3, "17/10", true), // CC
    row("CALL nn", 3, "17", true), // CD
    row("ADC A,n", 2, "7", true), // CE
    row("RST 08h", 1, "11", true), // CF
    row("RET NC", 1, "11/5", true), // D0
    row("POP DE", 1, "10", true), // D1
    row("JP NC,nn", 3, "10", true), // D2
    row("OUT (n),A", 2, "11", true), // D3
    row("CALL NC,nn", 3, "17/10", true), // D4
    row("PUSH DE", 1, "11", true), // D5
    row("SUB n", 2, "7", true), // D6
    row("RST 10h", 1, "11", true), // D7
    row("RET C", 1, "11/5", true), // D8
    row("EXX", 1, "4", true), // D9
    row("JP C,nn", 3, "10", true), // DA
    row("IN A,(n)", 2, "11", true), // DB
    row("CALL C,nn", 3, "17/10", true), // DC
    row("*DD prefix*", 1, "-", true), // DD
    row("SBC A,n", 2, "7", true), // DE
    row("RST 18h", 1, "11", true), // DF
    row("RET PO", 1, "11/5", true), // E0
    row("POP HL", 1, "10", true), // E1
    row("JP PO,nn", 3, "10", true), // E2
    row("EX (SP),HL", 1, "19", true), // E3
    row("CALL PO,nn", 3, "17/10", true), // E4
    row("PUSH HL", 1, "11", true), // E5
    row("AND n", 2, "7", true), // E6
    row("RST 20h", 1, "11", true), // E7
    row("RET PE", 1, "11/5", true), // E8
    row("JP (HL)", 1, "4", true), // E9
    row("JP PE,nn", 3, "10", true), // EA
    row("EX DE,HL", 1, "4", true), // EB
    row("CALL PE,nn", 3, "17/10", true), // EC
    row("*ED prefix*", 1, "-", true), // ED
    row("XOR n", 2, "7", true), // EE
    row("RST 28h", 1, "11", true), // EF
    row("RET P", 1, "11/5", true), // F0
    row("POP AF", 1, "10", true), // F1
    row("JP P,nn", 3, "10", true), // F2
    row("DI", 1, "4", true), // F3
    row("CALL P,nn", 3, "17/10", true), // F4
    row("PUSH AF", 1, "11", true), // F5
    row("OR n", 2, "7", true), // F6
    row("RST 30h", 1, "11", true), // F7
    row("RET M", 1, "11/5", true), // F8
    row("LD SP,HL", 1, "6", true), // F9
    row("JP M,nn", 3, "10", true), // FA
    row("EI", 1, "4", true), // FB
    row("CALL M,nn", 3, "17/10", true), // FC
    row("*FD prefix*", 1, "-", true), // FD
    row("CP n", 2, "7", true), // FE
    row("RST 38h", 1, "11", true), // FF
];

/// `CB`-prefixed opcodes.
pub static CB: [Option<Row>; 256] = [
    row("RLC B", 2, "8", true), // 00
    row("RLC C", 2, "8", true), // 01
    row("RLC D", 2, "8", true), // 02
    row("RLC E", 2, "8", true), // 03
    row("RLC H", 2, "8", true), // 04
    row("RLC L", 2, "8", true), // 05
    row("RLC (HL)", 2, "15", true), // 06
    row("RLC A", 2, "8", true), // 07
    row("RRC B", 2, "8", true), // 08
    row("RRC C", 2, "8", true), // 09
    row("RRC D", 2, "8", true), // 0A
    row("RRC E", 2, "8", true), // 0B
    row("RRC H", 2, "8", true), // 0C
    row("RRC L", 2, "8", true), // 0D
    row("RRC (HL)", 2, "15", true), // 0E
    row("RRC A", 2, "8", true), // 0F
    row("RL B", 2, "8", true), // 10
    row("RL C", 2, "8", true), // 11
    row("RL D", 2, "8", true), // 12
    row("RL E", 2, "8", true), // 13
    row("RL H", 2, "8", true), // 14
    row("RL L", 2, "8", true), // 15
    row("RL (HL)", 2, "15", true), // 16
    row("RL A", 2, "8", true), // 17
    row("RR B", 2, "8", true), // 18
    row("RR C", 2, "8", true), // 19
    row("RR D", 2, "8", true), // 1A
    row("RR E", 2, "8", true), // 1B
    row("RR H", 2, "8", true), // 1C
    row("RR L", 2, "8", true), // 1D
    row("RR (HL)", 2, "15", true), // 1E
    row("RR A", 2, "8", true), // 1F
    row("SLA B", 2, "8", true), // 20
    row("SLA C", 2, "8", true), // 21
    row("SLA D", 2, "8", true), // 22
    row("SLA E", 2, "8", true), // 23
    row("SLA H", 2, "8", true), // 24
    row("SLA L", 2, "8", true), // 25
    row("SLA (HL)", 2, "15", true), // 26
    row("SLA A", 2, "8", true), // 27
    row("SRA B", 2, "8", true), // 28
    row("SRA C", 2, "8", true), // 29
    row("SRA D", 2, "8", true), // 2A
    row("SRA E", 2, "8", true), // 2B
    row("SRA H", 2, "8", true), // 2C
    row("SRA L", 2, "8", true), // 2D
    row("SRA (HL)", 2, "15", true), // 2E
    row("SRA A", 2, "8", true), // 2F
    row("SLL B", 2, "8", false), // 30
    row("SLL C", 2, "8", false), // 31
    row("SLL D", 2, "8", false), // 32
    row("SLL E", 2, "8", false), // 33
    row("SLL H", 2, "8", false), // 34
    row("SLL L", 2, "8", false), // 35
    row("SLL (HL)", 2, "15", false), // 36
    row("SLL A", 2, "8", false), // 37
    row("SRL B", 2, "8", true), // 38
    row("SRL C", 2, "8", true), // 39
    row("SRL D", 2, "8", true), // 3A
    row("SRL E", 2, "8", true), // 3B
    row("SRL H", 2, "8", true), // 3C
    row("SRL L", 2, "8", true), // 3D
    row("SRL (HL)", 2, "15", true), // 3E
    row("SRL A", 2, "8", true), // 3F
    row("BIT 0,B", 2, "8", true), // 40
    row("BIT 0,C", 2, "8", true), // 41
    row("BIT 0,D", 2, "8", true), // 42
    row("BIT 0,E", 2, "8", true), // 43
    row("BIT 0,H", 2, "8", true), // 44
    row("BIT 0,L", 2, "8", true), // 45
    row("BIT 0,(HL)", 2, "12", true), // 46
    row("BIT 0,A", 2, "8", true), // 47
    row("BIT 1,B", 2, "8", true), // 48
    row("BIT 1,C", 2, "8", true), // 49
    row("BIT 1,D", 2, "8", true), // 4A
    row("BIT 1,E", 2, "8", true), // 4B
    row("BIT 1,H", 2, "8", true), // 4C
    row("BIT 1,L", 2, "8", true), // 4D
    row("BIT 1,(HL)", 2, "12", true), // 4E
    row("BIT 1,A", 2, "8", true), // 4F
    row("BIT 2,B", 2, "8", true), // 50
    row("BIT 2,C", 2, "8", true), // 51
    row("BIT 2,D", 2, "8", true), // 52
    row("BIT 2,E", 2, "8", true), // 53
    row("BIT 2,H", 2, "8", true), // 54
    row("BIT 2,L", 2, "8", true), // 55
    row("BIT 2,(HL)", 2, "12", true), // 56
    row("BIT 2,A", 2, "8", true), // 57
    row("BIT 3,B", 2, "8", true), // 58
    row("BIT 3,C", 2, "8", true), // 59
    row("BIT 3,D", 2, "8", true), // 5A
    row("BIT 3,E", 2, "8", true), // 5B
    row("BIT 3,H", 2, "8", true), // 5C
    row("BIT 3,L", 2, "8", true), // 5D
    row("BIT 3,(HL)", 2, "12", true), // 5E
    row("BIT 3,A", 2, "8", true), // 5F
    row("BIT 4,B", 2, "8", true), // 60
    row("BIT 4,C", 2, "8", true), // 61
    row("BIT 4,D", 2, "8", true), // 62
    row("BIT 4,E", 2, "8", true), // 63
    row("BIT 4,H", 2, "8", true), // 64
    row("BIT 4,L", 2, "8", true), // 65
    row("BIT 4,(HL)", 2, "12", true), // 66
    row("BIT 4,A", 2, "8", true), // 67
    row("BIT 5,B", 2, "8", true), // 68
    row("BIT 5,C", 2, "8", true), // 69
    row("BIT 5,D", 2, "8", true), // 6A
    row("BIT 5,E", 2, "8", true), // 6B
    row("BIT 5,H", 2, "8", true), // 6C
    row("BIT 5,L", 2, "8", true), // 6D
    row("BIT 5,(HL)", 2, "12", true), // 6E
    row("BIT 5,A", 2, "8", true), // 6F
    row("BIT 6,B", 2, "8", true), // 70
    row("BIT 6,C", 2, "8", true), // 71
    row("BIT 6,D", 2, "8", true), // 72
    row("BIT 6,E", 2, "8", true), // 73
    row("BIT 6,H", 2, "8", true), // 74
    row("BIT 6,L", 2, "8", true), // 75
    row("BIT 6,(HL)", 2, "12", true), // 76
    row("BIT 6,A", 2, "8", true), // 77
    row("BIT 7,B", 2, "8", true), // 78
    row("BIT 7,C", 2, "8", true), // 79
    row("BIT 7,D", 2, "8", true), // 7A
    row("BIT 7,E", 2, "8", true), // 7B
    row("BIT 7,H", 2, "8", true), // 7C
    row("BIT 7,L", 2, "8", true), // 7D
    row("BIT 7,(HL)", 2, "12", true), // 7E
    row("BIT 7,A", 2, "8", true), // 7F
    row("RES 0,B", 2, "8", true), // 80
    row("RES 0,C", 2, "8", true), // 81
    row("RES 0,D", 2, "8", true), // 82
    row("RES 0,E", 2, "8", true), // 83
    row("RES 0,H", 2, "8", true), // 84
    row("RES 0,L", 2, "8", true), // 85
    row("RES 0,(HL)", 2, "15", true), // 86
    row("RES 0,A", 2, "8", true), // 87
    row("RES 1,B", 2, "8", true), // 88
    row("RES 1,C", 2, "8", true), // 89
    row("RES 1,D", 2, "8", true), // 8A
    row("RES 1,E", 2, "8", true), // 8B
    row("RES 1,H", 2, "8", true), // 8C
    row("RES 1,L", 2, "8", true), // 8D
    row("RES 1,(HL)", 2, "15", true), // 8E
    row("RES 1,A", 2, "8", true), // 8F
    row("RES 2,B", 2, "8", true), // 90
    row("RES 2,C", 2, "8", true), // 91
    row("RES 2,D", 2, "8", true), // 92
    row("RES 2,E", 2, "8", true), // 93
    row("RES 2,H", 2, "8", true), // 94
    row("RES 2,L", 2, "8", true), // 95
    row("RES 2,(HL)", 2, "15", true), // 96
    row("RES 2,A", 2, "8", true), // 97
    row("RES 3,B", 2, "8", true), // 98
    row("RES 3,C", 2, "8", true), // 99
    row("RES 3,D", 2, "8", true), // 9A
    row("RES 3,E", 2, "8", true), // 9B
    row("RES 3,H", 2, "8", true), // 9C
    row("RES 3,L", 2, "8", true), // 9D
    row("RES 3,(HL)", 2, "15", true), // 9E
    row("RES 3,A", 2, "8", true), // 9F
    row("RES 4,B", 2, "8", true), // A0
    row("RES 4,C", 2, "8", true), // A1
    row("RES 4,D", 2, "8", true), // A2
    row("RES 4,E", 2, "8", true), // A3
    row("RES 4,H", 2, "8", true), // A4
    row("RES 4,L", 2, "8", true), // A5
    row("RES 4,(HL)", 2, "15", true), // A6
    row("RES 4,A", 2, "8", true), // A7
    row("RES 5,B", 2, "8", true), // A8
    row("RES 5,C", 2, "8", true), // A9
    row("RES 5,D", 2, "8", true), // AA
    row("RES 5,E", 2, "8", true), // AB
    row("RES 5,H", 2, "8", true), // AC
    row("RES 5,L", 2, "8", true), // AD
    row("RES 5,(HL)", 2, "15", true), // AE
    row("RES 5,A", 2, "8", true), // AF
    row("RES 6,B", 2, "8", true), // B0
    row("RES 6,C", 2, "8", true), // B1
    row("RES 6,D", 2, "8", true), // B2
    row("RES 6,E", 2, "8", true), // B3
    row("RES 6,H", 2, "8", true), // B4
    row("RES 6,L", 2, "8", true), // B5
    row("RES 6,(HL)", 2, "15", true), // B6
    row("RES 6,A", 2, "8", true), // B7
    row("RES 7,B", 2, "8", true), // B8
    row("RES 7,C", 2, "8", true), // B9
    row("RES 7,D", 2, "8", true), // BA
    row("RES 7,E", 2, "8", true), // BB
    row("RES 7,H", 2, "8", true), // BC
    row("RES 7,L", 2, "8", true), // BD
    row("RES 7,(HL)", 2, "15", true), // BE
    row("RES 7,A", 2, "8", true), // BF
    row("SET 0,B", 2, "8", true), // C0
    row("SET 0,C", 2, "8", true), // C1
    row("SET 0,D", 2, "8", true), // C2
    row("SET 0,E", 2, "8", true), // C3
    row("SET 0,H", 2, "8", true), // C4
    row("SET 0,L", 2, "8", true), // C5
    row("SET 0,(HL)", 2, "15", true), // C6
    row("SET 0,A", 2, "8", true), // C7
    row("SET 1,B", 2, "8", true), // C8
    row("SET 1,C", 2, "8", true), // C9
    row("SET 1,D", 2, "8", true), // CA
    row("SET 1,E", 2, "8", true), // CB
    row("SET 1,H", 2, "8", true), // CC
    row("SET 1,L", 2, "8", true), // CD
    row("SET 1,(HL)", 2, "15", true), // CE
    row("SET 1,A", 2, "8", true), // CF
    row("SET 2,B", 2, "8", true), // D0
    row("SET 2,C", 2, "8", true), // D1
    row("SET 2,D", 2, "8", true), // D2
    row("SET 2,E", 2, "8", true), // D3
    row("SET 2,H", 2, "8", true), // D4
    row("SET 2,L", 2, "8", true), // D5
    row("SET 2,(HL)", 2, "15", true), // D6
    row("SET 2,A", 2, "8", true), // D7
    row("SET 3,B", 2, "8", true), // D8
    row("SET 3,C", 2, "8", true), // D9
    row("SET 3,D", 2, "8", true), // DA
    row("SET 3,E", 2, "8", true), // DB
    row("SET 3,H", 2, "8", true), // DC
    row("SET 3,L", 2, "8", true), // DD
    row("SET 3,(HL)", 2, "15", true), // DE
    row("SET 3,A", 2, "8", true), // DF
    row("SET 4,B", 2, "8", true), // E0
    row("SET 4,C", 2, "8", true), // E1
    row("SET 4,D", 2, "8", true), // E2
    row("SET 4,E", 2, "8", true), // E3
    row("SET 4,H", 2, "8", true), // E4
    row("SET 4,L", 2, "8", true), // E5
    row("SET 4,(HL)", 2, "15", true), // E6
    row("SET 4,A", 2, "8", true), // E7
    row("SET 5,B", 2, "8", true), // E8
    row("SET 5,C", 2, "8", true), // E9
    row("SET 5,D", 2, "8", true), // EA
    row("SET 5,E", 2, "8", true), // EB
    row("SET 5,H", 2, "8", true), // EC
    row("SET 5,L", 2, "8", true), // ED
    row("SET 5,(HL)", 2, "15", true), // EE
    row("SET 5,A", 2, "8", true), // EF
    row("SET 6,B", 2, "8", true), // F0
    row("SET 6,C", 2, "8", true), // F1
    row("SET 6,D", 2, "8", true), // F2
    row("SET 6,E", 2, "8", true), // F3
    row("SET 6,H", 2, "8", true), // F4
    row("SET 6,L", 2, "8", true), // F5
    row("SET 6,(HL)", 2, "15", true), // F6
    row("SET 6,A", 2, "8", true), // F7
    row("SET 7,B", 2, "8", true), // F8
    row("SET 7,C", 2, "8", true), // F9
    row("SET 7,D", 2, "8", true), // FA
    row("SET 7,E", 2, "8", true), // FB
    row("SET 7,H", 2, "8", true), // FC
    row("SET 7,L", 2, "8", true), // FD
    row("SET 7,(HL)", 2, "15", true), // FE
    row("SET 7,A", 2, "8", true), // FF
];

/// `ED`-prefixed opcodes.
pub static ED: [Option<Row>; 256] = [
    row("NONI, NOP", 2, "8", false), // 00
    row("NONI, NOP", 2, "8", false), // 01
    row("NONI, NOP", 2, "8", false), // 02
    row("NONI, NOP", 2, "8", false), // 03
    row("NONI, NOP", 2, "8", false), // 04
    row("NONI, NOP", 2, "8", false), // 05
    row("NONI, NOP", 2, "8", false), // 06
    row("NONI, NOP", 2, "8", false), // 07
    row("NONI, NOP", 2, "8", false), // 08
    row("NONI, NOP", 2, "8", false), // 09
    row("NONI, NOP", 2, "8", false), // 0A
    row("NONI, NOP", 2, "8", false), // 0B
    row("NONI, NOP", 2, "8", false), // 0C
    row("NONI, NOP", 2, "8", false), // 0D
    row("NONI, NOP", 2, "8", false), // 0E
    row("NONI, NOP", 2, "8", false), // 0F
    row("NONI, NOP", 2, "8", false), // 10
    row("NONI, NOP", 2, "8", false), // 11
    row("NONI, NOP", 2, "8", false), // 12
    row("NONI, NOP", 2, "8", false), // 13
    row("NONI, NOP", 2, "8", false), // 14
    row("NONI, NOP", 2, "8", false), // 15
    row("NONI, NOP", 2, "8", false), // 16
    row("NONI, NOP", 2, "8", false), // 17
    row("NONI, NOP", 2, "8", false), // 18
    row("NONI, NOP", 2, "8", false), // 19
    row("NONI, NOP", 2, "8", false), // 1A
    row("NONI, NOP", 2, "8", false), // 1B
    row("NONI, NOP", 2, "8", false), // 1C
    row("NONI, NOP", 2, "8", false), // 1D
    row("NONI, NOP", 2, "8", false), // 1E
    row("NONI, NOP", 2, "8", false), // 1F
    row("NONI, NOP", 2, "8", false), // 20
    row("NONI, NOP", 2, "8", false), // 21
    row("NONI, NOP", 2, "8", false), // 22
    row("NONI, NOP", 2, "8", false), // 23
    row("NONI, NOP", 2, "8", false), // 24
    row("NONI, NOP", 2, "8", false), // 25
    row("NONI, NOP", 2, "8", false), // 26
    row("NONI, NOP", 2, "8", false), // 27
    row("NONI, NOP", 2, "8", false), // 28
    row("NONI, NOP", 2, "8", false), // 29
    row("NONI, NOP", 2, "8", false), // 2A
    row("NONI, NOP", 2, "8", false), // 2B
    row("NONI, NOP", 2, "8", false), // 2C
    row("NONI, NOP", 2, "8", false), // 2D
    row("NONI, NOP", 2, "8", false), // 2E
    row("NONI, NOP", 2, "8", false), // 2F
    row("NONI, NOP", 2, "8", false), // 30
    row("NONI, NOP", 2, "8", false), // 31
    row("NONI, NOP", 2, "8", false), // 32
    row("NONI, NOP", 2, "8", false), // 33
    row("NONI, NOP", 2, "8", false), // 34
    row("NONI, NOP", 2, "8", false), // 35
    row("NONI, NOP", 2, "8", false), // 36
    row("NONI, NOP", 2, "8", false), // 37
    row("NONI, NOP", 2, "8", false), // 38
    row("NONI, NOP", 2, "8", false), // 39
    row("NONI, NOP", 2, "8", false), // 3A
    row("NONI, NOP", 2, "8", false), // 3B
    row("NONI, NOP", 2, "8", false), // 3C
    row("NONI, NOP", 2, "8", false), // 3D
    row("NONI, NOP", 2, "8", false), // 3E
    row("NONI, NOP", 2, "8", false), // 3F
    row("IN B,(C)", 2, "12", true), // 40
    row("OUT (C),B", 2, "12", true), // 41
    row("SBC HL,BC", 2, "15", true), // 42
    row("LD (nn),BC", 4, "20", true), // 43
    row("NEG", 2, "8", true), // 44
    row("RETN", 2, "14", true), // 45
    row("IM 0", 2, "8", true), // 46
    row("LD I,A", 2, "9", true), // 47
    row("IN C,(C)", 2, "12", true), // 48
    row("OUT (C),C", 2, "12", true), // 49
    row("ADC HL,BC", 2, "15", true), // 4A
    row("LD BC,(nn)", 4, "20", true), // 4B
    row("NEG", 2, "8", false), // 4C
    row("RETI", 2, "14", true), // 4D
    row("IM 0/1", 2, "8", false), // 4E
    row("LD R,A", 2, "9", true), // 4F
    row("IN D,(C)", 2, "12", true), // 50
    row("OUT (C),D", 2, "12", true), // 51
    row("SBC HL,DE", 2, "15", true), // 52
    row("LD (nn),DE", 4, "20", true), // 53
    row("NEG", 2, "8", false), // 54
    row("RETN", 2, "14", false), // 55
    row("IM 1", 2, "8", true), // 56
    row("LD A,I", 2, "9", true), // 57
    row("IN E,(C)", 2, "12", true), // 58
    row("OUT (C),E", 2, "12", true), // 59
    row("ADC HL,DE", 2, "15", true), // 5A
    row("LD DE,(nn)", 4, "20", true), // 5B
    row("NEG", 2, "8", false), // 5C
    row("RETN", 2, "14", false), // 5D
    row("IM 2", 2, "8", true), // 5E
    row("LD A,R", 2, "9", true), // 5F
    row("IN H,(C)", 2, "12", true), // 60
    row("OUT (C),H", 2, "12", true), // 61
    row("SBC HL,HL", 2, "15", true), // 62
    row("LD (nn),HL", 4, "20", true), // 63
    row("NEG", 2, "8", false), // 64
    row("RETN", 2, "14", false), // 65
    row("IM 0", 2, "8", false), // 66
    row("RRD", 2, "18", true), // 67
    row("IN L,(C)", 2, "12", true), // 68
    row("OUT (C),L", 2, "12", true), // 69
    row("ADC HL,HL", 2, "15", true), // 6A
    row("LD HL,(nn)", 4, "20", true), // 6B
    row("NEG", 2, "8", false), // 6C
    row("RETN", 2, "14", false), // 6D
    row("IM 0/1", 2, "8", false), // 6E
    row("RLD", 2, "18", true), // 6F
    row("IN (C)", 2, "12", false), // 70
    row("OUT (C),0", 2, "12", false), // 71
    row("SBC HL,SP", 2, "15", true), // 72
    row("LD (nn),SP", 4, "20", true), // 73
    row("NEG", 2, "8", false), // 74
    row("RETN", 2, "14", false), // 75
    row("IM 1", 2, "8", false), // 76
    row("NOP", 2, "8", false), // 77
    row("IN A,(C)", 2, "12", true), // 78
    row("OUT (C),A", 2, "12", true), // 79
    row("ADC HL,SP", 2, "15", true), // 7A
    row("LD SP,(nn)", 4, "20", true), // 7B
    row("NEG", 2, "8", false), // 7C
    row("RETN", 2, "14", false), // 7D
    row("IM 2", 2, "8", false), // 7E
    row("NOP", 2, "8", false), // 7F
    row("NONI, NOP", 2, "8", false), // 80
    row("NONI, NOP", 2, "8", false), // 81
    row("NONI, NOP", 2, "8", false), // 82
    row("NONI, NOP", 2, "8", false), // 83
    row("NONI, NOP", 2, "8", false), // 84
    row("NONI, NOP", 2, "8", false), // 85
    row("NONI, NOP", 2, "8", false), // 86
    row("NONI, NOP", 2, "8", false), // 87
    row("NONI, NOP", 2, "8", false), // 88
    row("NONI, NOP", 2, "8", false), // 89
    row("NONI, NOP", 2, "8", false), // 8A
    row("NONI, NOP", 2, "8", false), // 8B
    row("NONI, NOP", 2, "8", false), // 8C
    row("NONI, NOP", 2, "8", false), // 8D
    row("NONI, NOP", 2, "8", false), // 8E
    row("NONI, NOP", 2, "8", false), // 8F
    row("NONI, NOP", 2, "8", false), // 90
    row("NONI, NOP", 2, "8", false), // 91
    row("NONI, NOP", 2, "8", false), // 92
    row("NONI, NOP", 2, "8", false), // 93
    row("NONI, NOP", 2, "8", false), // 94
    row("NONI, NOP", 2, "8", false), // 95
    row("NONI, NOP", 2, "8", false), // 96
    row("NONI, NOP", 2, "8", false), // 97
    row("NONI, NOP", 2, "8", false), // 98
    row("NONI, NOP", 2, "8", false), // 99
    row("NONI, NOP", 2, "8", false), // 9A
    row("NONI, NOP", 2, "8", false), // 9B
    row("NONI, NOP", 2, "8", false), // 9C
    row("NONI, NOP", 2, "8", false), // 9D
    row("NONI, NOP", 2, "8", false), // 9E
    row("NONI, NOP", 2, "8", false), // 9F
    row("LDI", 2, "16", true), // A0
    row("CPI", 2, "16", true), // A1
    row("INI", 2, "16", true), // A2
    row("OUTI", 2, "16", true), // A3
    row("NONI, NOP", 2, "8", false), // A4
    row("NONI, NOP", 2, "8", false), // A5
    row("NONI, NOP", 2, "8", false), // A6
    row("NONI, NOP", 2, "8", false), // A7
    row("LDD", 2, "16", true), // A8
    row("CPD", 2, "16", true), // A9
    row("IND", 2, "16", true), // AA
    row("OUTD", 2, "16", true), // AB
    row("NONI, NOP", 2, "8", false), // AC
    row("NONI, NOP", 2, "8", false), // AD
    row("NONI, NOP", 2, "8", false), // AE
    row("NONI, NOP", 2, "8", false), // AF
    row("LDIR", 2, "21/16", true), // B0
    row("CPIR", 2, "21/16", true), // B1
    row("INIR", 2, "21/16", true), // B2
    row("OTIR", 2, "21/16", true), // B3
    row("NONI, NOP", 2, "8", false), // B4
    row("NONI, NOP", 2, "8", false), // B5
    row("NONI, NOP", 2, "8", false), // B6
    row("NONI, NOP", 2, "8", false), // B7
    row("LDDR", 2, "21/16", true), // B8
    row("CPDR", 2, "21/16", true), // B9
    row("INDR", 2, "21/16", true), // BA
    row("OTDR", 2, "21/16", true), // BB
    row("NONI, NOP", 2, "8", false), // BC
    row("NONI, NOP", 2, "8", false), // BD
    row("NONI, NOP", 2, "8", false), // BE
    row("NONI, NOP", 2, "8", false), // BF
    row("NONI, NOP", 2, "8", false), // C0
    row("NONI, NOP", 2, "8", false), // C1
    row("NONI, NOP", 2, "8", false), // C2
    row("NONI, NOP", 2, "8", false), // C3
    row("NONI, NOP", 2, "8", false), // C4
    row("NONI, NOP", 2, "8", false), // C5
    row("NONI, NOP", 2, "8", false), // C6
    row("NONI, NOP", 2, "8", false), // C7
    row("NONI, NOP", 2, "8", false), // C8
    row("NONI, NOP", 2, "8", false), // C9
    row("NONI, NOP", 2, "8", false), // CA
    row("NONI, NOP", 2, "8", false), // CB
    row("NONI, NOP", 2, "8", false), // CC
    row("NONI, NOP", 2, "8", false), // CD
    row("NONI, NOP", 2, "8", false), // CE
    row("NONI, NOP", 2, "8", false), // CF
    row("NONI, NOP", 2, "8", false), // D0
    row("NONI, NOP", 2, "8", false), // D1
    row("NONI, NOP", 2, "8", false), // D2
    row("NONI, NOP", 2, "8", false), // D3
    row("NONI, NOP", 2, "8", false), // D4
    row("NONI, NOP", 2, "8", false), // D5
    row("NONI, NOP", 2, "8", false), // D6
    row("NONI, NOP", 2, "8", false), // D7
    row("NONI, NOP", 2, "8", false), // D8
    row("NONI, NOP", 2, "8", false), // D9
    row("NONI, NOP", 2, "8", false), // DA
    row("NONI, NOP", 2, "8", false), // DB
    row("NONI, NOP", 2, "8", false), // DC
    row("NONI, NOP", 2, "8", false), // DD
    row("NONI, NOP", 2, "8", false), // DE
    row("NONI, NOP", 2, "8", false), // DF
    row("NONI, NOP", 2, "8", false), // E0
    row("NONI, NOP", 2, "8", false), // E1
    row("NONI, NOP", 2, "8", false), // E2
    row("NONI, NOP", 2, "8", false), // E3
    row("NONI, NOP", 2, "8", false), // E4
    row("NONI, NOP", 2, "8", false), // E5
    row("NONI, NOP", 2, "8", false), // E6
    row("NONI, NOP", 2, "8", false), // E7
    row("NONI, NOP", 2, "8", false), // E8
    row("NONI, NOP", 2, "8", false), // E9
    row("NONI, NOP", 2, "8", false), // EA
    row("NONI, NOP", 2, "8", false), // EB
    row("NONI, NOP", 2, "8", false), // EC
    row("NONI, NOP", 2, "8", false), // ED
    row("NONI, NOP", 2, "8", false), // EE
    row("NONI, NOP", 2, "8", false), // EF
    row("NONI, NOP", 2, "8", false), // F0
    row("NONI, NOP", 2, "8", false), // F1
    row("NONI, NOP", 2, "8", false), // F2
    row("NONI, NOP", 2, "8", false), // F3
    row("NONI, NOP", 2, "8", false), // F4
    row("NONI, NOP", 2, "8", false), // F5
    row("NONI, NOP", 2, "8", false), // F6
    row("NONI, NOP", 2, "8", false), // F7
    row("NONI, NOP", 2, "8", false), // F8
    row("NONI, NOP", 2, "8", false), // F9
    row("NONI, NOP", 2, "8", false), // FA
    row("NONI, NOP", 2, "8", false), // FB
    row("NONI, NOP", 2, "8", false), // FC
    row("NONI, NOP", 2, "8", false), // FD
    row("NONI, NOP", 2, "8", false), // FE
    row("NONI, NOP", 2, "8", false), // FF
];

/// `DD`-prefixed opcodes. `FD` is identical with `IY` for `IX`.
pub static DD: [Option<Row>; 256] = [
    None, // 00
    None, // 01
    None, // 02
    None, // 03
    None, // 04
    None, // 05
    None, // 06
    None, // 07
    None, // 08
    row("ADD IX,BC", 2, "15", true), // 09
    None, // 0A
    None, // 0B
    None, // 0C
    None, // 0D
    None, // 0E
    None, // 0F
    None, // 10
    None, // 11
    None, // 12
    None, // 13
    None, // 14
    None, // 15
    None, // 16
    None, // 17
    None, // 18
    row("ADD IX,DE", 2, "15", true), // 19
    None, // 1A
    None, // 1B
    None, // 1C
    None, // 1D
    None, // 1E
    None, // 1F
    None, // 20
    row("LD IX,nn", 4, "14", true), // 21
    row("LD (nn),IX", 4, "20", true), // 22
    row("INC IX", 2, "10", true), // 23
    row("INC IXH", 2, "8", false), // 24
    row("DEC IXH", 2, "8", false), // 25
    row("LD IXH,n", 3, "11", false), // 26
    None, // 27
    None, // 28
    row("ADD IX,IX", 2, "15", true), // 29
    row("LD IX,(nn)", 4, "20", true), // 2A
    row("DEC IX", 2, "10", true), // 2B
    row("INC IXL", 2, "8", false), // 2C
    row("DEC IXL", 2, "8", false), // 2D
    row("LD IXL,n", 3, "11", false), // 2E
    None, // 2F
    None, // 30
    None, // 31
    None, // 32
    None, // 33
    row("INC (IX+d)", 3, "23", true), // 34
    row("DEC (IX+d)", 3, "23", true), // 35
    row("LD (IX+d),n", 4, "19", true), // 36
    None, // 37
    None, // 38
    row("ADD IX,SP", 2, "15", true), // 39
    None, // 3A
    None, // 3B
    None, // 3C
    None, // 3D
    None, // 3E
    None, // 3F
    None, // 40
    None, // 41
    None, // 42
    None, // 43
    row("LD B,IXH", 2, "8", false), // 44
    row("LD B,IXL", 2, "8", false), // 45
    row("LD B,(IX+d)", 3, "19", true), // 46
    None, // 47
    None, // 48
    None, // 49
    None, // 4A
    None, // 4B
    row("LD C,IXH", 2, "8", false), // 4C
    row("LD C,IXL", 2, "8", false), // 4D
    row("LD C,(IX+d)", 3, "19", true), // 4E
    None, // 4F
    None, // 50
    None, // 51
    None, // 52
    None, // 53
    row("LD D,IXH", 2, "8", false), // 54
    row("LD D,IXL", 2, "8", false), // 55
    row("LD D,(IX+d)", 3, "19", true), // 56
    None, // 57
    None, // 58
    None, // 59
    None, // 5A
    None, // 5B
    row("LD E,IXH", 2, "8", false), // 5C
    row("LD E,IXL", 2, "8", false), // 5D
    row("LD E,(IX+d)", 3, "19", true), // 5E
    None, // 5F
    row("LD IXH,B", 2, "8", false), // 60
    row("LD IXH,C", 2, "8", false), // 61
    row("LD IXH,D", 2, "8", false), // 62
    row("LD IXH,E", 2, "8", false), // 63
    row("LD IXH,IXH", 2, "8", false), // 64
    row("LD IXH,IXL", 2, "8", false), // 65
    row("LD H,(IX+d)", 3, "19", true), // 66
    row("LD IXH,A", 2, "8", false), // 67
    row("LD IXL,B", 2, "8", false), // 68
    row("LD IXL,C", 2, "8", false), // 69
    row("LD IXL,D", 2, "8", false), // 6A
    row("LD IXL,E", 2, "8", false), // 6B
    row("LD IXL,IXH", 2, "8", false), // 6C
    row("LD IXL,IXL", 2, "8", false), // 6D
    row("LD L,(IX+d)", 3, "19", true), // 6E
    row("LD IXL,A", 2, "8", false), // 6F
    row("LD (IX+d),B", 3, "19", true), // 70
    row("LD (IX+d),C", 3, "19", true), // 71
    row("LD (IX+d),D", 3, "19", true), // 72
    row("LD (IX+d),E", 3, "19", true), // 73
    row("LD (IX+d),H", 3, "19", true), // 74
    row("LD (IX+d),L", 3, "19", true), // 75
    None, // 76
    row("LD (IX+d),A", 3, "19", true), // 77
    None, // 78
    None, // 79
    None, // 7A
    None, // 7B
    row("LD A,IXH", 2, "8", false), // 7C
    row("LD A,IXL", 2, "8", false), // 7D
    row("LD A,(IX+d)", 3, "19", true), // 7E
    None, // 7F
    None, // 80
    None, // 81
    None, // 82
    None, // 83
    row("ADD A,IXH", 2, "8", false), // 84
    row("ADD A,IXL", 2, "8", false), // 85
    row("ADD A,(IX+d)", 3, "19", true), // 86
    None, // 87
    None, // 88
    None, // 89
    None, // 8A
    None, // 8B
    row("ADC A,IXH", 2, "8", false), // 8C
    row("ADC A,IXL", 2, "8", false), // 8D
    row("ADC A,(IX+d)", 3, "19", true), // 8E
    None, // 8F
    None, // 90
    None, // 91
    None, // 92
    None, // 93
    row("SUB IXH", 2, "8", false), // 94
    row("SUB IXL", 2, "8", false), // 95
    row("SUB (IX+d)", 3, "19", true), // 96
    None, // 97
    None, // 98
    None, // 99
    None, // 9A
    None, // 9B
    row("SBC A,IXH", 2, "8", false), // 9C
    row("SBC A,IXL", 2, "8", false), // 9D
    row("SBC A,(IX+d)", 3, "19", true), // 9E
    None, // 9F
    None, // A0
    None, // A1
    None, // A2
    None, // A3
    row("AND IXH", 2, "8", false), // A4
    row("AND IXL", 2, "8", false), // A5
    row("AND (IX+d)", 3, "19", true), // A6
    None, // A7
    None, // A8
    None, // A9
    None, // AA
    None, // AB
    row("XOR IXH", 2, "8", false), // AC
    row("XOR IXL", 2, "8", false), // AD
    row("XOR (IX+d)", 3, "19", true), // AE
    None, // AF
    None, // B0
    None, // B1
    None, // B2
    None, // B3
    row("OR IXH", 2, "8", false), // B4
    row("OR IXL", 2, "8", false), // B5
    row("OR (IX+d)", 3, "19", true), // B6
    None, // B7
    None, // B8
    None, // B9
    None, // BA
    None, // BB
    row("CP IXH", 2, "8", false), // BC
    row("CP IXL", 2, "8", false), // BD
    row("CP (IX+d)", 3, "19", true), // BE
    None, // BF
    None, // C0
    None, // C1
    None, // C2
    None, // C3
    None, // C4
    None, // C5
    None, // C6
    None, // C7
    None, // C8
    None, // C9
    None, // CA
    None, // CB
    None, // CC
    None, // CD
    None, // CE
    None, // CF
    None, // D0
    None, // D1
    None, // D2
    None, // D3
    None, // D4
    None, // D5
    None, // D6
    None, // D7
    None, // D8
    None, // D9
    None, // DA
    None, // DB
    None, // DC
    None, // DD
    None, // DE
    None, // DF
    None, // E0
    row("POP IX", 2, "14", true), // E1
    None, // E2
    row("EX (SP),IX", 2, "23", true), // E3
    None, // E4
    row("PUSH IX", 2, "15", true), // E5
    None, // E6
    None, // E7
    None, // E8
    row("JP (IX)", 2, "8", true), // E9
    None, // EA
    None, // EB
    None, // EC
    None, // ED
    None, // EE
    None, // EF
    None, // F0
    None, // F1
    None, // F2
    None, // F3
    None, // F4
    None, // F5
    None, // F6
    None, // F7
    None, // F8
    row("LD SP,IX", 2, "10", true), // F9
    None, // FA
    None, // FB
    None, // FC
    None, // FD
    None, // FE
    None, // FF
];

/// `DD CB d`-prefixed opcodes. `FD CB d` is identical with `IY` for `IX`.
pub static DDCB: [Option<Row>; 256] = [
    row("LD B,RLC (IX+d)", 4, "23", false), // 00
    row("LD C,RLC (IX+d)", 4, "23", false), // 01
    row("LD D,RLC (IX+d)", 4, "23", false), // 02
    row("LD E,RLC (IX+d)", 4, "23", false), // 03
    row("LD H,RLC (IX+d)", 4, "23", false), // 04
    row("LD L,RLC (IX+d)", 4, "23", false), // 05
    row("RLC (IX+d)", 4, "23", true), // 06
    row("LD A,RLC (IX+d)", 4, "23", false), // 07
    row("LD B,RRC (IX+d)", 4, "23", false), // 08
    row("LD C,RRC (IX+d)", 4, "23", false), // 09
    row("LD D,RRC (IX+d)", 4, "23", false), // 0A
    row("LD E,RRC (IX+d)", 4, "23", false), // 0B
    row("LD H,RRC (IX+d)", 4, "23", false), // 0C
    row("LD L,RRC (IX+d)", 4, "23", false), // 0D
    row("RRC (IX+d)", 4, "23", true), // 0E
    row("LD A,RRC (IX+d)", 4, "23", false), // 0F
    row("LD B,RL (IX+d)", 4, "23", false), // 10
    row("LD C,RL (IX+d)", 4, "23", false), // 11
    row("LD D,RL (IX+d)", 4, "23", false), // 12
    row("LD E,RL (IX+d)", 4, "23", false), // 13
    row("LD H,RL (IX+d)", 4, "23", false), // 14
    row("LD L,RL (IX+d)", 4, "23", false), // 15
    row("RL (IX+d)", 4, "23", true), // 16
    row("LD A,RL (IX+d)", 4, "23", false), // 17
    row("LD B,RR (IX+d)", 4, "23", false), // 18
    row("LD C,RR (IX+d)", 4, "23", false), // 19
    row("LD D,RR (IX+d)", 4, "23", false), // 1A
    row("LD E,RR (IX+d)", 4, "23", false), // 1B
    row("LD H,RR (IX+d)", 4, "23", false), // 1C
    row("LD L,RR (IX+d)", 4, "23", false), // 1D
    row("RR (IX+d)", 4, "23", true), // 1E
    row("LD A,RR (IX+d)", 4, "23", false), // 1F
    row("LD B,SLA (IX+d)", 4, "23", false), // 20
    row("LD C,SLA (IX+d)", 4, "23", false), // 21
    row("LD D,SLA (IX+d)", 4, "23", false), // 22
    row("LD E,SLA (IX+d)", 4, "23", false), // 23
    row("LD H,SLA (IX+d)", 4, "23", false), // 24
    row("LD L,SLA (IX+d)", 4, "23", false), // 25
    row("SLA (IX+d)", 4, "23", true), // 26
    row("LD A,SLA (IX+d)", 4, "23", false), // 27
    row("LD B,SRA (IX+d)", 4, "23", false), // 28
    row("LD C,SRA (IX+d)", 4, "23", false), // 29
    row("LD D,SRA (IX+d)", 4, "23", false), // 2A
    row("LD E,SRA (IX+d)", 4, "23", false), // 2B
    row("LD H,SRA (IX+d)", 4, "23", false), // 2C
    row("LD L,SRA (IX+d)", 4, "23", false), // 2D
    row("SRA (IX+d)", 4, "23", true), // 2E
    row("LD A,SRA (IX+d)", 4, "23", false), // 2F
    row("LD B,SLL (IX+d)", 4, "23", false), // 30
    row("LD C,SLL (IX+d)", 4, "23", false), // 31
    row("LD D,SLL (IX+d)", 4, "23", false), // 32
    row("LD E,SLL (IX+d)", 4, "23", false), // 33
    row("LD H,SLL (IX+d)", 4, "23", false), // 34
    row("LD L,SLL (IX+d)", 4, "23", false), // 35
    row("SLL (IX+d)", 4, "23", false), // 36
    row("LD A,SLL (IX+d)", 4, "23", false), // 37
    row("LD B,SRL (IX+d)", 4, "23", false), // 38
    row("LD C,SRL (IX+d)", 4, "23", false), // 39
    row("LD D,SRL (IX+d)", 4, "23", false), // 3A
    row("LD E,SRL (IX+d)", 4, "23", false), // 3B
    row("LD H,SRL (IX+d)", 4, "23", false), // 3C
    row("LD L,SRL (IX+d)", 4, "23", false), // 3D
    row("SRL (IX+d)", 4, "23", true), // 3E
    row("LD A,SRL (IX+d)", 4, "23", false), // 3F
    row("BIT 0,(IX+d)", 4, "20", false), // 40
    row("BIT 0,(IX+d)", 4, "20", false), // 41
    row("BIT 0,(IX+d)", 4, "20", false), // 42
    row("BIT 0,(IX+d)", 4, "20", false), // 43
    row("BIT 0,(IX+d)", 4, "20", false), // 44
    row("BIT 0,(IX+d)", 4, "20", false), // 45
    row("BIT 0,(IX+d)", 4, "20", true), // 46
    row("BIT 0,(IX+d)", 4, "20", false), // 47
    row("BIT 1,(IX+d)", 4, "20", false), // 48
    row("BIT 1,(IX+d)", 4, "20", false), // 49
    row("BIT 1,(IX+d)", 4, "20", false), // 4A
    row("BIT 1,(IX+d)", 4, "20", false), // 4B
    row("BIT 1,(IX+d)", 4, "20", false), // 4C
    row("BIT 1,(IX+d)", 4, "20", false), // 4D
    row("BIT 1,(IX+d)", 4, "20", true), // 4E
    row("BIT 1,(IX+d)", 4, "20", false), // 4F
    row("BIT 2,(IX+d)", 4, "20", false), // 50
    row("BIT 2,(IX+d)", 4, "20", false), // 51
    row("BIT 2,(IX+d)", 4, "20", false), // 52
    row("BIT 2,(IX+d)", 4, "20", false), // 53
    row("BIT 2,(IX+d)", 4, "20", false), // 54
    row("BIT 2,(IX+d)", 4, "20", false), // 55
    row("BIT 2,(IX+d)", 4, "20", true), // 56
    row("BIT 2,(IX+d)", 4, "20", false), // 57
    row("BIT 3,(IX+d)", 4, "20", false), // 58
    row("BIT 3,(IX+d)", 4, "20", false), // 59
    row("BIT 3,(IX+d)", 4, "20", false), // 5A
    row("BIT 3,(IX+d)", 4, "20", false), // 5B
    row("BIT 3,(IX+d)", 4, "20", false), // 5C
    row("BIT 3,(IX+d)", 4, "20", false), // 5D
    row("BIT 3,(IX+d)", 4, "20", true), // 5E
    row("BIT 3,(IX+d)", 4, "20", false), // 5F
    row("BIT 4,(IX+d)", 4, "20", false), // 60
    row("BIT 4,(IX+d)", 4, "20", false), // 61
    row("BIT 4,(IX+d)", 4, "20", false), // 62
    row("BIT 4,(IX+d)", 4, "20", false), // 63
    row("BIT 4,(IX+d)", 4, "20", false), // 64
    row("BIT 4,(IX+d)", 4, "20", false), // 65
    row("BIT 4,(IX+d)", 4, "20", true), // 66
    row("BIT 4,(IX+d)", 4, "20", false), // 67
    row("BIT 5,(IX+d)", 4, "20", false), // 68
    row("BIT 5,(IX+d)", 4, "20", false), // 69
    row("BIT 5,(IX+d)", 4, "20", false), // 6A
    row("BIT 5,(IX+d)", 4, "20", false), // 6B
    row("BIT 5,(IX+d)", 4, "20", false), // 6C
    row("BIT 5,(IX+d)", 4, "20", false), // 6D
    row("BIT 5,(IX+d)", 4, "20", true), // 6E
    row("BIT 5,(IX+d)", 4, "20", false), // 6F
    row("BIT 6,(IX+d)", 4, "20", false), // 70
    row("BIT 6,(IX+d)", 4, "20", false), // 71
    row("BIT 6,(IX+d)", 4, "20", false), // 72
    row("BIT 6,(IX+d)", 4, "20", false), // 73
    row("BIT 6,(IX+d)", 4, "20", false), // 74
    row("BIT 6,(IX+d)", 4, "20", false), // 75
    row("BIT 6,(IX+d)", 4, "20", true), // 76
    row("BIT 6,(IX+d)", 4, "20", false), // 77
    row("BIT 7,(IX+d)", 4, "20", false), // 78
    row("BIT 7,(IX+d)", 4, "20", false), // 79
    row("BIT 7,(IX+d)", 4, "20", false), // 7A
    row("BIT 7,(IX+d)", 4, "20", false), // 7B
    row("BIT 7,(IX+d)", 4, "20", false), // 7C
    row("BIT 7,(IX+d)", 4, "20", false), // 7D
    row("BIT 7,(IX+d)", 4, "20", true), // 7E
    row("BIT 7,(IX+d)", 4, "20", false), // 7F
    row("LD B,RES 0,(IX+d)", 4, "23", false), // 80
    row("LD C,RES 0,(IX+d)", 4, "23", false), // 81
    row("LD D,RES 0,(IX+d)", 4, "23", false), // 82
    row("LD E,RES 0,(IX+d)", 4, "23", false), // 83
    row("LD H,RES 0,(IX+d)", 4, "23", false), // 84
    row("LD L,RES 0,(IX+d)", 4, "23", false), // 85
    row("RES 0,(IX+d)", 4, "23", true), // 86
    row("LD A,RES 0,(IX+d)", 4, "23", false), // 87
    row("LD B,RES 1,(IX+d)", 4, "23", false), // 88
    row("LD C,RES 1,(IX+d)", 4, "23", false), // 89
    row("LD D,RES 1,(IX+d)", 4, "23", false), // 8A
    row("LD E,RES 1,(IX+d)", 4, "23", false), // 8B
    row("LD H,RES 1,(IX+d)", 4, "23", false), // 8C
    row("LD L,RES 1,(IX+d)", 4, "23", false), // 8D
    row("RES 1,(IX+d)", 4, "23", true), // 8E
    row("LD A,RES 1,(IX+d)", 4, "23", false), // 8F
    row("LD B,RES 2,(IX+d)", 4, "23", false), // 90
    row("LD C,RES 2,(IX+d)", 4, "23", false), // 91
    row("LD D,RES 2,(IX+d)", 4, "23", false), // 92
    row("LD E,RES 2,(IX+d)", 4, "23", false), // 93
    row("LD H,RES 2,(IX+d)", 4, "23", false), // 94
    row("LD L,RES 2,(IX+d)", 4, "23", false), // 95
    row("RES 2,(IX+d)", 4, "23", true), // 96
    row("LD A,RES 2,(IX+d)", 4, "23", false), // 97
    row("LD B,RES 3,(IX+d)", 4, "23", false), // 98
    row("LD C,RES 3,(IX+d)", 4, "23", false), // 99
    row("LD D,RES 3,(IX+d)", 4, "23", false), // 9A
    row("LD E,RES 3,(IX+d)", 4, "23", false), // 9B
    row("LD H,RES 3,(IX+d)", 4, "23", false), // 9C
    row("LD L,RES 3,(IX+d)", 4, "23", false), // 9D
    row("RES 3,(IX+d)", 4, "23", true), // 9E
    row("LD A,RES 3,(IX+d)", 4, "23", false), // 9F
    row("LD B,RES 4,(IX+d)", 4, "23", false), // A0
    row("LD C,RES 4,(IX+d)", 4, "23", false), // A1
    row("LD D,RES 4,(IX+d)", 4, "23", false), // A2
    row("LD E,RES 4,(IX+d)", 4, "23", false), // A3
    row("LD H,RES 4,(IX+d)", 4, "23", false), // A4
    row("LD L,RES 4,(IX+d)", 4, "23", false), // A5
    row("RES 4,(IX+d)", 4, "23", true), // A6
    row("LD A,RES 4,(IX+d)", 4, "23", false), // A7
    row("LD B,RES 5,(IX+d)", 4, "23", false), // A8
    row("LD C,RES 5,(IX+d)", 4, "23", false), // A9
    row("LD D,RES 5,(IX+d)", 4, "23", false), // AA
    row("LD E,RES 5,(IX+d)", 4, "23", false), // AB
    row("LD H,RES 5,(IX+d)", 4, "23", false), // AC
    row("LD L,RES 5,(IX+d)", 4, "23", false), // AD
    row("RES 5,(IX+d)", 4, "23", true), // AE
    row("LD A,RES 5,(IX+d)", 4, "23", false), // AF
    row("LD B,RES 6,(IX+d)", 4, "23", false), // B0
    row("LD C,RES 6,(IX+d)", 4, "23", false), // B1
    row("LD D,RES 6,(IX+d)", 4, "23", false), // B2
    row("LD E,RES 6,(IX+d)", 4, "23", false), // B3
    row("LD H,RES 6,(IX+d)", 4, "23", false), // B4
    row("LD L,RES 6,(IX+d)", 4, "23", false), // B5
    row("RES 6,(IX+d)", 4, "23", true), // B6
    row("LD A,RES 6,(IX+d)", 4, "23", false), // B7
    row("LD B,RES 7,(IX+d)", 4, "23", false), // B8
    row("LD C,RES 7,(IX+d)", 4, "23", false), // B9
    row("LD D,RES 7,(IX+d)", 4, "23", false), // BA
    row("LD E,RES 7,(IX+d)", 4, "23", false), // BB
    row("LD H,RES 7,(IX+d)", 4, "23", false), // BC
    row("LD L,RES 7,(IX+d)", 4, "23", false), // BD
    row("RES 7,(IX+d)", 4, "23", true), // BE
    row("LD A,RES 7,(IX+d)", 4, "23", false), // BF
    row("LD B,SET 0,(IX+d)", 4, "23", false), // C0
    row("LD C,SET 0,(IX+d)", 4, "23", false), // C1
    row("LD D,SET 0,(IX+d)", 4, "23", false), // C2
    row("LD E,SET 0,(IX+d)", 4, "23", false), // C3
    row("LD H,SET 0,(IX+d)", 4, "23", false), // C4
    row("LD L,SET 0,(IX+d)", 4, "23", false), // C5
    row("SET 0,(IX+d)", 4, "23", true), // C6
    row("LD A,SET 0,(IX+d)", 4, "23", false), // C7
    row("LD B,SET 1,(IX+d)", 4, "23", false), // C8
    row("LD C,SET 1,(IX+d)", 4, "23", false), // C9
    row("LD D,SET 1,(IX+d)", 4, "23", false), // CA
    row("LD E,SET 1,(IX+d)", 4, "23", false), // CB
    row("LD H,SET 1,(IX+d)", 4, "23", false), // CC
    row("LD L,SET 1,(IX+d)", 4, "23", false), // CD
    row("SET 1,(IX+d)", 4, "23", true), // CE
    row("LD A,SET 1,(IX+d)", 4, "23", false), // CF
    row("LD B,SET 2,(IX+d)", 4, "23", false), // D0
    row("LD C,SET 2,(IX+d)", 4, "23", false), // D1
    row("LD D,SET 2,(IX+d)", 4, "23", false), // D2
    row("LD E,SET 2,(IX+d)", 4, "23", false), // D3
    row("LD H,SET 2,(IX+d)", 4, "23", false), // D4
    row("LD L,SET 2,(IX+d)", 4, "23", false), // D5
    row("SET 2,(IX+d)", 4, "23", true), // D6
    row("LD A,SET 2,(IX+d)", 4, "23", false), // D7
    row("LD B,SET 3,(IX+d)", 4, "23", false), // D8
    row("LD C,SET 3,(IX+d)", 4, "23", false), // D9
    row("LD D,SET 3,(IX+d)", 4, "23", false), // DA
    row("LD E,SET 3,(IX+d)", 4, "23", false), // DB
    row("LD H,SET 3,(IX+d)", 4, "23", false), // DC
    row("LD L,SET 3,(IX+d)", 4, "23", false), // DD
    row("SET 3,(IX+d)", 4, "23", true), // DE
    row("LD A,SET 3,(IX+d)", 4, "23", false), // DF
    row("LD B,SET 4,(IX+d)", 4, "23", false), // E0
    row("LD C,SET 4,(IX+d)", 4, "23", false), // E1
    row("LD D,SET 4,(IX+d)", 4, "23", false), // E2
    row("LD E,SET 4,(IX+d)", 4, "23", false), // E3
    row("LD H,SET 4,(IX+d)", 4, "23", false), // E4
    row("LD L,SET 4,(IX+d)", 4, "23", false), // E5
    row("SET 4,(IX+d)", 4, "23", true), // E6
    row("LD A,SET 4,(IX+d)", 4, "23", false), // E7
    row("LD B,SET 5,(IX+d)", 4, "23", false), // E8
    row("LD C,SET 5,(IX+d)", 4, "23", false), // E9
    row("LD D,SET 5,(IX+d)", 4, "23", false), // EA
    row("LD E,SET 5,(IX+d)", 4, "23", false), // EB
    row("LD H,SET 5,(IX+d)", 4, "23", false), // EC
    row("LD L,SET 5,(IX+d)", 4, "23", false), // ED
    row("SET 5,(IX+d)", 4, "23", true), // EE
    row("LD A,SET 5,(IX+d)", 4, "23", false), // EF
    row("LD B,SET 6,(IX+d)", 4, "23", false), // F0
    row("LD C,SET 6,(IX+d)", 4, "23", false), // F1
    row("LD D,SET 6,(IX+d)", 4, "23", false), // F2
    row("LD E,SET 6,(IX+d)", 4, "23", false), // F3
    row("LD H,SET 6,(IX+d)", 4, "23", false), // F4
    row("LD L,SET 6,(IX+d)", 4, "23", false), // F5
    row("SET 6,(IX+d)", 4, "23", true), // F6
    row("LD A,SET 6,(IX+d)", 4, "23", false), // F7
    row("LD B,SET 7,(IX+d)", 4, "23", false), // F8
    row("LD C,SET 7,(IX+d)", 4, "23", false), // F9
    row("LD D,SET 7,(IX+d)", 4, "23", false), // FA
    row("LD E,SET 7,(IX+d)", 4, "23", false), // FB
    row("LD H,SET 7,(IX+d)", 4, "23", false), // FC
    row("LD L,SET 7,(IX+d)", 4, "23", false), // FD
    row("SET 7,(IX+d)", 4, "23", true), // FE
    row("LD A,SET 7,(IX+d)", 4, "23", false), // FF
];

